In [1]:
import tensorflow as tf
print(f"TensorFlow Version: {tf.__version__}")

TensorFlow Version: 2.19.0


In [12]:
scalar_tensor = tf.constant(7)
print("Scalar Tensor:", scalar_tensor)


vector_tensor = tf.constant([1, 2, 3])
print("Vector Tensor:", vector_tensor)


matrix_tensor = tf.constant([[1, 2], [3, 4]])
print("Matrix Tensor:\n", matrix_tensor)

Scalar Tensor: tf.Tensor(7, shape=(), dtype=int32)
Vector Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix Tensor:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [13]:
tensor_a = tf.constant([[10., 20.], [30., 40.]])
tensor_b = tf.constant([[ 1.,  2.], [ 3.,  4.]])

print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)


addition_result = tensor_a + tensor_b
print("\nAddition (A + B):\n", addition_result)


subtraction_result = tensor_a - tensor_b
print("\nSubtraction (A - B):\n", subtraction_result)


multiplication_result = tensor_a * tensor_b
print("\nElement-wise Multiplication (A * B):\n", multiplication_result)


division_result = tensor_a / tensor_b
print("\nElement-wise Division (A / B):\n", division_result)

Tensor A:
 tf.Tensor(
[[10. 20.]
 [30. 40.]], shape=(2, 2), dtype=float32)
Tensor B:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Addition (A + B):
 tf.Tensor(
[[11. 22.]
 [33. 44.]], shape=(2, 2), dtype=float32)

Subtraction (A - B):
 tf.Tensor(
[[ 9. 18.]
 [27. 36.]], shape=(2, 2), dtype=float32)

Element-wise Multiplication (A * B):
 tf.Tensor(
[[ 10.  40.]
 [ 90. 160.]], shape=(2, 2), dtype=float32)

Element-wise Division (A / B):
 tf.Tensor(
[[10. 10.]
 [10. 10.]], shape=(2, 2), dtype=float32)


In [14]:
integer_tensor = tf.constant([1, 2, 3, 4, 5])
print("Integer Tensor:", integer_tensor)
print("  Data Type:", integer_tensor.dtype)
print("  Shape:", integer_tensor.shape)


float_tensor = tf.constant([1.0, 2.5, 3.8, 4.1], dtype=tf.float32)
print("\nFloat Tensor:", float_tensor)
print("  Data Type:", float_tensor.dtype)
print("  Shape:", float_tensor.shape)


matrix_tensor = tf.constant([[10, 20], [30, 40], [50, 60]])
print("\nMatrix Tensor:", matrix_tensor)
print("  Data Type:", matrix_tensor.dtype)
print("  Shape:", matrix_tensor.shape)

Integer Tensor: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
  Data Type: <dtype: 'int32'>
  Shape: (5,)

Float Tensor: tf.Tensor([1.  2.5 3.8 4.1], shape=(4,), dtype=float32)
  Data Type: <dtype: 'float32'>
  Shape: (4,)

Matrix Tensor: tf.Tensor(
[[10 20]
 [30 40]
 [50 60]], shape=(3, 2), dtype=int32)
  Data Type: <dtype: 'int32'>
  Shape: (3, 2)


In [15]:
numpy_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print("Original NumPy Array:\n", numpy_array)
print("  NumPy Array Type:", type(numpy_array))
print("  NumPy Array Shape:", numpy_array.shape)
print("  NumPy Array Dtype:", numpy_array.dtype)


tensorflow_tensor = tf.constant(numpy_array)


print("\nConverted TensorFlow Tensor:\n", tensorflow_tensor)
print("  TensorFlow Tensor Type:", type(tensorflow_tensor))
print("  TensorFlow Tensor Shape:", tensorflow_tensor.shape)
print("  TensorFlow Tensor Dtype:", tensorflow_tensor.dtype)

Original NumPy Array:
 [[1 2 3]
 [4 5 6]]
  NumPy Array Type: <class 'numpy.ndarray'>
  NumPy Array Shape: (2, 3)
  NumPy Array Dtype: int32

Converted TensorFlow Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
  TensorFlow Tensor Type: <class 'tensorflow.python.framework.ops.EagerTensor'>
  TensorFlow Tensor Shape: (2, 3)
  TensorFlow Tensor Dtype: <dtype: 'int32'>
